
version: "3.9"

services:
  rest-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: rest-server-container
    ports:
      - "5000:5000"
    networks:
      - my-network

  robot-tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    container_name: robot-tests-container
    command: robot --variable SERVER_URL:http://rest-server-container:5000 --outputdir /reports .
    depends_on:
      - rest-server
    volumes:
      - ./reports:/reports
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
